"""
Stanford SU2 3D CFD Automation Driver.
Generates 3D unstructured surface/volume mesh scripts and production-ready .cfg files.
"""

from typing import Dict, Any, Optional
import os
import numpy as np
from ..geometry.wing_3d import Wing3D


class SU2Driver3D:
    """
    Automated SU2 3D CFD setup orchestrator for RANS and Euler calculations.
    """

    def __init__(self, wing: Wing3D):
        self.wing = wing

    def generate_config(
        self,
        mach: float = 0.82,
        alpha_deg: float = 2.5,
        reynolds: float = 2.5e7,
        solver_type: str = "RANS",
        turbulence_model: str = "SA",
        num_iterations: int = 1500,
        cfl_number: float = 5.0,
        output_filepath: Optional[str] = None,
    ) -> str:
        """
        Generates a complete production-grade SU2 3D configuration file.
        """
        solver_key = "RANS" if solver_type.upper() == "RANS" else "EULER"
        turb_key = "SPALART_ALLMARAS" if turbulence_model.upper() == "SA" else "SST"

        cfg = f"""%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                              %
% SU2 3D Configuration File - Generated by AeroWing AI Pro                      %
% Wing Name: {self.wing.name}                                                   %
%                                                                              %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% ------------- DIRECT, ADJOINT, AND LINEARIZED PROBLEM DEFINITION ------------%
SOLVER= {solver_key}
KIND_TURB_MODEL= {turb_key}
MATH_PROBLEM= DIRECT
RESTART_SOL= NO

% ----------- COMPRESSIBLE FREE-STREAM DEFINITION -----------------------------%
MACH_NUMBER= {mach:.4f}
AOA= {alpha_deg:.4f}
SIDESLIP_ANGLE= 0.0
FREESTREAM_TEMPERATURE= 216.65
FREESTREAM_PRESSURE= 22632.0
REYNOLDS_NUMBER= {reynolds:.4e}
REYNOLDS_LENGTH= {self.wing.mac:.4f}

% ---------------------- REFERENCE VALUES -------------------------------------%
REF_ORIGIN_MOMENT_X = {self.wing.y_mac * np.tan(np.radians(self.wing.sweep_le_deg)) + 0.25 * self.wing.mac:.4f}
REF_ORIGIN_MOMENT_Y = 0.0000
REF_ORIGIN_MOMENT_Z = 0.0000
REF_AREA= {self.wing.s_ref:.4f}
REF_LENGTH= {self.wing.mac:.4f}
REF_SEMI_SPAN= {self.wing.semi_span:.4f}

% -------------------- BOUNDARY CONDITIONS ------------------------------------%
MARKER_HEATFLUX= ( wing, 0.0 )
MARKER_FAR= ( farfield )
MARKER_SYM= ( symmetry )
MARKER_MONITORING= ( wing )
MARKER_DESIGNING= ( wing )

% ------------------------ SURFACES IDENTIFICATION ----------------------------%
MARKER_PLOTTING= ( wing )

% ------------- COMMON PARAMETERS DEFINING THE NUMERICAL METHOD ---------------%
NUM_METHOD_GRAD= GREEN_GAUSS
CFL_NUMBER= {cfl_number:.1f}
CFL_ADAPT= YES
CFL_ADAPT_PARAM= ( 0.1, 1.2, 1.0, 50.0 )

% ------------------------ LINEAR SOLVER DEFINITION ---------------------------%
LINEAR_SOLVER= FGMRES
LINEAR_SOLVER_PREC= ILU
LINEAR_SOLVER_ERROR= 1E-6
LINEAR_SOLVER_ITER= 10

% -------------------- FLOW NUMERICAL METHOD DEFINITION -----------------------%
CONV_NUM_METHOD_FLOW= ROE
MUSCL_FLOW= YES
SLOPE_LIMITER_FLOW= VENKATAKRISHNAN
VENKAT_LIMITER_COEFF= 0.05
TIME_DISCRE_FLOW= EULER_IMPLICIT

% ----------------- TURBULENT NUMERICAL METHOD DEFINITION ---------------------%
CONV_NUM_METHOD_TURB= SCALAR_UPWIND
TIME_DISCRE_TURB= EULER_IMPLICIT

% --------------------------- CONVERGENCE PARAMETERS --------------------------%
ITER= {num_iterations}
CONV_FIELD= RMS_DENSITY
CONV_RESIDUAL_MINVAL= -8
CONV_STARTITER= 10

% ------------------------- INPUT/OUTPUT INFORMATION --------------------------%
MESH_FILENAME= mesh_3d.su2
MESH_FORMAT= SU2
SOLUTION_FILENAME= solution_flow.dat
TABULAR_FORMAT= CSV
OUTPUT_FILES= ( RESTART, PARAVIEW, SURFACE_PARAVIEW )
CONV_FILENAME= history
HISTORY_OUTPUT= ( ITER, RMS_RES, LIFT, DRAG, MOMENT_Z, EFFICIENCY )
"""
        if output_filepath:
            os.makedirs(os.path.dirname(os.path.abspath(output_filepath)), exist_ok=True)
            with open(output_filepath, "w") as f:
                f.write(cfg)

        return cfg
